---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: AFX 하드웨어를 설치한 후 클러스터 설정을 완료할 수 있습니다.  이 프로세스에는 순차적으로 수행해야 하는 두 가지 관련 구성 단계가 포함됩니다. 
---
= AFX 스토리지 시스템 ONTAP 클러스터 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 하드웨어를 설치한 후 ONTAP 클러스터 설정을 완료할 수 있습니다.  이 프로세스에는 순차적으로 수행해야 하는 두 가지 관련 구성 단계가 포함됩니다.



== 초기 클러스터 설정 수행

노트북 장치를 AFX 클러스터에 연결하고 여러 가지 글로벌 구성 값을 설정할 수 있습니다.

.이 작업에 관하여
AFX 클러스터에는 처음에 구성해야 하는 4개의 영역이 있습니다.  처음 세 가지는 필수이고 마지막 것은 선택 사항입니다.

.시작하기 전에
다음 정보가 필요합니다.

* 클러스터 관리 IP 주소
+
클러스터 관리 IP 주소는 클러스터 관리자가 관리 SVM에 액세스하고 클러스터를 관리하는 데 사용하는 클러스터 관리 인터페이스의 고유한 IPv4 주소입니다.  이 IP 주소는 귀하의 조직에서 IP 주소를 할당하는 관리자로부터 얻을 수 있습니다.

* 네트워크 서브넷 마스크
+
클러스터 설정 중에 ONTAP 구성에 적합한 네트워크 인터페이스 세트가 필요합니다.  필요한 경우 권장 사항을 조정할 수 있습니다.



다음 사항도 필요합니다.

* 네트워크 게이트웨이 IP 주소
* DNS 도메인 이름
* DNS 이름 서버 IP 주소
* NTP 서버 IP 주소
* 서브넷 마스크


.단계
. 클러스터 네트워크를 알아보세요.
+
.. 노트북을 관리 스위치에 연결하고 네트워크 컴퓨터와 장치에 액세스하세요.
.. 파일 탐색기를 엽니다.
.. *네트워크*를 선택한 다음 마우스 오른쪽 버튼을 클릭하고 *새로 고침*을 선택합니다.
.. ONTAP 아이콘을 선택한 다음 화면에 표시된 모든 인증서를 수락합니다.
+
시스템 관리자 사용자 인터페이스가 표시됩니다.



. 관리자 비밀번호를 설정하세요.
+
비밀번호를 제공하고 확인하세요. `admin` 계정. *계속*을 선택하세요.

. 클러스터와 컨트롤러 노드의 IP 주소를 구성합니다.
+
IP 주소와 서브넷 마스크를 제공하세요.

. 네트워크 서비스를 구성합니다. *계속*을 선택하세요.
+
DNS 및 NTP 서버에 대한 세부 정보를 정의합니다.

. 선택적으로 암호화를 설정합니다.
+
클러스터 암호화에 대한 세부 정보를 정의할 수 있습니다. *계속*을 선택하세요.



.다음은 무엇입니까?
시스템 관리자 로그인 페이지로 리디렉션됩니다.  설명된 단계를 수행하십시오.<<클러스터 설정 완료>> .



== 클러스터 설정 완료

초기 구성을 수행한 후 System Manager를 사용하여 ONTAP 클러스터 설정을 완료할 수 있습니다.

.이 작업에 관하여
AFX 시스템 ONTAP 클러스터에는 설정 중에 구성된 세 가지 영역이 있습니다.  가능하다면 세 가지를 모두 완료하세요. 하지만 첫 번째 것만 필수입니다.

.시작하기 전에
다음 정보가 필요합니다.

* VLAN 구성 세부 정보.
* NAS 및/또는 S3 구성 세부정보.


.단계
. 초기 클러스터 설정 시 제공한 관리자 계정을 사용하여 시스템 관리자에 Sign in .  오른쪽 상단에 세 가지 구성 옵션이 있는 팝업 창이 표시됩니다.
. *VLAN 및 태그 지정*을 선택하고 사용자 환경에 적합한 네트워크 옵션을 선택하세요.
. *네트워크 서비스*를 선택하고 기본 데이터 SVM에 대한 클라이언트 액세스 프로토콜을 구성합니다.
. *데이터 컨테이너*를 선택하고 볼륨이나 S3 버킷을 만듭니다.


.다음은 무엇입니까?
당신은해야합니다link:../get-started/prepare-cluster-admin.html["AFX 관리를 준비하세요"] 프로덕션 환경에서 AFX 클러스터를 사용하기 전에.

.관련 정보
* link:../administer/configure-svm.html["AFX SVM 구성"]
* link:../get-started/prepare-cluster-admin.html["AFX 관리를 준비하세요"]

