---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: afx, afx 1k, install, setup, hardware, deploy 
summary: AFX 1K 보관 시스템과 보관 선반용 레일 키트를 설치하는 방법과 캐비닛이나 통신 랙에 AFX 하드웨어를 고정하는 방법을 알아보세요. 
---
= AFX 1K 스토리지 시스템 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치를 설치한 후에는 AFX 1K 스토리지 시스템용 하드웨어를 설치해야 합니다.  먼저, 레일 키트를 설치합니다.  그런 다음 캐비닛이나 통신 랙에 보관 시스템을 설치하고 고정하세요.

.시작하기 전에
* 레일 키트와 함께 설명서가 포함되어 있는지 확인하세요.
* 보관 시스템과 보관 선반의 무게와 관련된 안전 문제를 이해하세요.
* 저장 시스템을 통과하는 공기 흐름은 베젤이나 엔드 캡이 설치된 전면에서 들어와 포트가 있는 후면으로 배출된다는 점을 이해하세요.


.단계
. 필요에 따라 키트에 포함된 설명서를 사용하여 보관 시스템과 보관 선반용 레일 키트를 설치하세요.
. 캐비닛이나 통신 랙에 컨트롤러를 설치하고 고정하세요.
+
.. 캐비닛이나 통신 랙 중앙의 레일에 보관 시스템을 놓고, 보관 시스템을 아래쪽에서 받쳐 제자리에 밀어 넣습니다.
.. 포함된 장착 나사를 사용하여 보관 시스템을 캐비닛이나 통신 랙에 고정합니다.


. 베젤을 컨트롤러 앞면에 부착합니다.
. AFX 1K 보관 시스템에 케이블 관리 장치가 포함되어 있는 경우 보관 시스템 뒷면에 부착하세요.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[케이블 관리 장치 설치]

. 보관 선반을 설치하고 고정하세요:
+
.. 보관 선반의 뒷면을 레일 위에 놓고 선반을 아래쪽에서 받쳐 캐비닛이나 통신 랙에 밀어 넣습니다.
+
일반적으로 저장 선반과 컨트롤러는 스위치와 가까운 곳에 설치해야 합니다.  여러 개의 보관 선반을 설치하는 경우 첫 번째 보관 선반을 컨트롤러 바로 위에 놓으세요.  두 번째 보관 선반을 컨트롤러 바로 아래에 놓으세요.  추가 보관 선반이 있을 때마다 이 패턴을 반복합니다.

.. 포함된 장착 나사를 사용하여 보관 선반을 캐비닛이나 통신 랙에 고정합니다.




.다음은 무엇인가요?
AFX 시스템용 하드웨어를 설치한 후 다음을 검토하세요.link:afx-cable-overview.html["AFX 1K 스토리지 시스템에 지원되는 케이블 구성"] .
