---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: afx, afx 1k, install, setup, requirements, cautions 
summary: AFX 1K 보관 컨트롤러와 보관 선반에 필요한 장비와 들어올릴 때의 주의사항을 검토하세요. 
---
= AFX 1K 스토리지 시스템 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 1K 보관 컨트롤러와 보관 선반에 필요한 장비와 들어올릴 때의 주의사항을 검토하세요.



[[equipment-needed-for-install]]
== 설치에 필요한 장비

AFX 1K 보관 시스템을 설치하려면 다음과 같은 장비와 도구가 필요합니다.

* 저장 시스템을 구성하기 위한 웹 브라우저 접속
* 정전기 방전(ESD) 스트랩
* 플래시
* USB/직렬 연결이 가능한 노트북 또는 콘솔
* 보관 선반 ID를 설정하기 위한 종이 클립 또는 좁은 팁 볼펜
* 필립스 #2 드라이버




[[lifting-precautions]]
== 리프팅 시 주의사항

AFX 스토리지 컨트롤러와 스토리지 선반은 무겁습니다.  이런 품목을 들어올리거나 옮길 때는 주의하세요.



[[storage-controller-weights]]
=== 스토리지 컨트롤러 무게

AFX 1K 스토리지 컨트롤러를 옮기거나 들어 올릴 때는 필요한 예방 조치를 취하세요.

AFX 1K 스토리지 컨트롤러는 최대 62.83lb(28.5kg)까지 나갈 수 있습니다. 스토리지 컨트롤러를 들어 올리려면 두 사람이 함께 들거나 유압 리프트를 사용하십시오.

.AFX 1K 컨트롤러를 들어 올릴 때 주의 사항.
image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFX 1K 리프팅 경고 아이콘]



[[storage-shelf-weights]]
=== 보관 선반 무게

선반을 옮기거나 들어 올릴 때는 필요한 예방 조치를 취하세요.

.NX224 선반
--
NX224 쉘프의 무게는 최대 60.1lb(27.3kg)입니다. 쉘프를 들어 올릴 때는 두 사람이 함께 들거나 유압 리프트를 사용하십시오. 쉘프의 무게 균형이 맞지 않는 것을 방지하기 위해 모든 구성품(앞쪽과 뒤쪽 모두)을 쉘프 안에 넣어 두십시오.

.NX224 쉘프 들어 올리기 주의 사항.
image::../media/drw_nx224_lifting_weight_ieops-2437.svg[NX224 NSM100 리프팅 주의]

.관련 정보
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["안전 정보 및 규정 고지 사항"^]


.다음은 무엇인가요?
하드웨어 요구 사항을 검토한 후link:prepare-hardware.html["AFX 1K 스토리지 시스템 설치를 준비하세요"] .

--