---
sidebar: sidebar 
permalink: install-setup/install-network-reqs.html 
keywords: shared storage cluster switch 
summary: ONTAP 9.9.1부터 Cisco Nexus 9364d-gx2a 스위치를 사용하여 스토리지와 클러스터 기능을 공유 스위치 시나리오로 결합할 수 있습니다. 
---
= AFX 1K 스토리지 시스템에 대한 네트워크 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFX 1K 스토리지 시스템에 연결하는 각 네트워크에 필요한 정보를 기록하세요.



== 네트워크 정보 수집

AFX 1K 스토리지 시스템 설치를 시작하기 전에 필요한 네트워크 정보를 수집하세요.

* 각 스토리지 시스템 컨트롤러와 해당 스위치에 대한 호스트 이름과 IP 주소입니다.
+
대부분의 스토리지 시스템 컨트롤러는 이더넷 서비스 포트(렌치 아이콘)에 연결하여 e0M 인터페이스를 통해 관리됩니다.

+
를 참조하세요 https://hwu.netapp.com["Hardware Universe"^] 최신 정보를 확인하세요.

* 클러스터 관리 IP 주소
+
클러스터 관리 IP 주소는 클러스터 관리자가 관리 스토리지 VM에 액세스하고 클러스터를 관리하는 데 사용하는 클러스터 관리 인터페이스의 고유한 IP 주소입니다.  이 IP 주소는 귀하의 조직에서 IP 주소를 할당하는 관리자로부터 얻을 수 있습니다.

* 네트워크 서브넷 마스크
+
클러스터 설정 중에 ONTAP 구성에 적합한 네트워크 인터페이스 세트를 권장합니다.  필요한 경우 권장 사항을 조정할 수 있습니다.

* 네트워크 게이트웨이 IP 주소
* 노드 관리 IP 주소(노드당 하나)
* DNS 도메인 이름
* DNS 이름 서버 IP 주소
* NTP 서버 IP 주소
* 데이터 서브넷 마스크
* 관리 네트워크 트래픽을 위한 IP 서브넷.




== Cisco 스위치에 대한 네트워크 요구 사항

Cisco Nexus 9332D-GX2B 및 9364D-GX2A 스위치 설치 및 유지관리를 위해서는 케이블 및 네트워크 요구 사항을 검토하세요.



=== 네트워크 요구 사항

모든 스위치 구성에는 다음 네트워크 정보가 필요합니다.

* 관리 네트워크 트래픽을 위한 IP 서브넷
* 각 스토리지 시스템 컨트롤러와 모든 해당 스위치에 대한 호스트 이름 및 IP 주소
* 를 참조하세요 https://hwu.netapp.com["Hardware Universe"^] 최신 정보를 확인하세요.




=== 케이블링 요구 사항

* 스위치에 적합한 수와 유형의 케이블과 케이블 커넥터가 있습니다. 를 참조하십시오 https://hwu.netapp.com["Hardware Universe"^] .
* 처음 구성하는 스위치 유형에 따라 포함된 콘솔 케이블을 사용하여 스위치 콘솔 포트에 연결해야 합니다.


.다음은 무엇인가요?
네트워크 요구 사항을 검토한 후link:cable-hardware.html["AFX 1K 스토리지 시스템의 컨트롤러와 스토리지 선반에 케이블을 연결합니다."] .
