---
sidebar: sidebar 
permalink: secure-data/prepare-secure-data.html 
keywords: afx, afx system, prepare, prepare secure, prepare secure data 
summary: AFX 데이터를 관리하기 전에 주요 개념과 기능에 대해 숙지해야 합니다. 
---
= AFX 스토리지 시스템 데이터 보안을 준비하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 데이터를 관리하기 전에 주요 개념과 기능에 대해 숙지해야 합니다.



== 용어 및 옵션

AFX 데이터 보안과 관련하여 알아야 할 용어가 몇 가지 있습니다.

랜섬웨어:: 랜섬웨어는 사용자가 접근할 수 없도록 파일을 암호화하는 악성 소프트웨어입니다. 일반적으로 데이터를 해독하려면 어떤 유형의 지불이 요구됩니다.  ONTAP ARP(자율 랜섬웨어 보호)와 같은 기능을 통해 랜섬웨어로부터 보호하는 솔루션을 제공합니다.
암호화:: 암호화는 적절한 승인 없이는 쉽게 읽을 수 없는 안전한 형식으로 데이터를 변환하는 프로세스입니다. ONTAP 저장된 데이터를 보호하기 위해 소프트웨어 기반 및 하드웨어 기반 암호화 기술을 모두 제공합니다. 이렇게 하면 저장 매체가 다른 용도로 사용되거나, 반환되거나, 분실되거나, 도난당하더라도 해당 정보를 읽을 수 없게 됩니다. 이러한 암호화 솔루션은 외부 키 관리 서버나 ONTAP 에서 제공하는 Onboard Key Manager를 사용하여 관리할 수 있습니다. 참조하다link:../secure-data/encrypt-data-at-rest.html["AFX 스토리지 시스템에서 저장 중인 데이터 암호화"] 자세한 내용은.
디지털 인증서 및 PKI:: 디지털 인증서는 공개 키의 소유권을 증명하는 데 사용되는 전자 문서입니다. 공개 키와 이와 관련된 개인 키는 다양한 방법으로 사용될 수 있는데, 일반적으로 TLS 및 IPsec와 같은 보다 큰 보안 프레임워크의 일부로서 신원을 확립하는 데 사용됩니다. 이러한 키와 지원 프로토콜 및 포맷 표준은 공개 키 인프라(PKI)의 기반을 형성합니다. 참조하다link:../administer/manage-certificates.html#generate-a-certificate-signing-request["AFX 스토리지 시스템에서 인증서 관리"] 자세한 내용은.
인터넷 프로토콜 보안:: IPsec은 IP 수준에서 네트워크 엔드포인트 간 트래픽 흐름에 대한 전송 중 데이터 암호화, 무결성 및 인증을 제공하는 인터넷 표준입니다.  NFS 및 SMB와 같은 상위 레벨 프로토콜을 포함하여 ONTAP 과 클라이언트 간의 모든 IP 트래픽을 보호합니다.  IPsec은 데이터에 대한 악의적인 재생 및 중간자 공격으로부터 보호해줍니다. 참조하다link:../secure-data/secure-ip-connections.html["AFX 스토리지 시스템의 보안 IP 연결"] 자세한 내용은.




== 관련 정보

* link:../administer/additional-ontap-svm.html["추가 AFX SVM 관리"]
* link:../get-started/prepare-cluster-admin.html["AFX 시스템 관리를 준비하세요"]

