---
sidebar: sidebar 
permalink: faq-ontap-afx.html 
keywords: afx, afx system, faq, frequently asked questions 
summary: 이 FAQ 목록은 고객이 AFX 스토리지 시스템에 대해 일반적으로 궁금해하는 질문에 대한 답변을 제공합니다.  여기에는 AFX를 더 자세히 살펴보거나 고급 관리 작업을 수행할 때 도움이 될 수 있는 개념과 용어가 포함되어 있습니다. 
---
= AFX 스토리지 시스템에 대한 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 FAQ 목록은 AFX 스토리지 시스템에 대해 궁금한 사항에 대한 답변을 제공합니다.  여기에는 AFX를 더 자세히 살펴보거나 고급 관리 작업을 수행할 때 도움이 될 수 있는 개념과 용어가 포함되어 있습니다.



== 일반적인

.ONTAP 성격이란 무엇인가요?
ONTAP 은 포괄적인 기능 세트와 광범위한 스토리지 요구 사항에 대한 적응성으로 유명한 견고하고 다재다능한 스토리지 플랫폼입니다.  이러한 유연성 덕분에 다양한 작업 부하를 가진 조직에 매우 적합한 선택이지만, 일부 고객은 특정 환경의 요구 사항에 맞춰 최적화된 맞춤형 스토리지 솔루션을 통해 이점을 얻을 수 있습니다.

이러한 특수한 요구 사항을 해결하기 위해 일부 NetApp 스토리지 시스템은 고유한 ONTAP 특성을 제공하며, 각각 고유한 고객 요구 사항을 지원하도록 설계된 기능 세트를 포함합니다.  ONTAP 개성은 일반적으로 하드웨어와 소프트웨어 기능의 조합으로 구성되며, 타겟 사용 사례에 최적화된 경험을 제공하도록 특별히 제작되었습니다.  NetApp 세 가지 ONTAP 특성을 제공합니다.

* *Unified ONTAP* - Unified ONTAP 특성은 최대의 유연성을 위해 NAS, SAN 및 S3 프로토콜을 지원하는 광범위한 데이터 관리 기능을 제공합니다. 이는 AFF 및 FAS 시스템뿐만 아니라 ONTAP Select 및 Cloud Volumes ONTAP 과 같은 가상화된 배포에서도 사용할 수 있는 NetApp 주력 제품입니다.
* *AFX* - AFX ONTAP 개성은 AI/ML 애플리케이션을 포함하여 고성능 NAS 및 S3 워크로드의 엄격한 요구 사항을 충족하도록 설계된 분산 솔루션을 제공합니다. AFX 시스템은 확장 가능하고 처리량이 높은 파일 및 개체 스토리지를 필요로 하는 고객을 위해 특수 기능을 제공합니다.
* * ASA r2* - ASA r2 ONTAP 개성은 SAN 전용 환경을 위해 특별히 설계된 분산 솔루션을 제공합니다. https://docs.netapp.com/us-en/asa-r2/["ASA r2 시스템"^]  블록 워크로드에 대한 스토리지 환경을 간소화하여 SAN 고객에게 최적화된 성능과 간소화된 관리를 제공합니다.


NetApp 이러한 고유한 ONTAP 특성을 제공함으로써 조직이 운영 요구 사항과 애플리케이션 작업 부하에 맞는 스토리지 솔루션을 선택할 수 있도록 지원합니다.

.NetApp 스토리지 시스템의 ONTAP 특성을 변경할 수 있나요?
아니요. ONTAP 스토리지 시스템의 특성은 변경할 수 없습니다.  예를 들어, Unified ONTAP 특성을 실행하는 FAS 또는 AFF 스토리지 시스템을 AFX 스토리지 시스템으로 변환하거나 업그레이드할 수 없습니다.

.다양한 ONTAP 특성에 대한 시스템 관리자 인터페이스는 모두 매우 유사해 보입니다.  특정 시스템의 성격을 어떻게 판단할 수 있나요?
시스템 관리자의 왼쪽 탐색 창에서 *클러스터*를 선택한 다음 *개요*를 선택합니다.  해당 페이지에 성격이 표시되는 것을 보실 수 있습니다.  또는 CLI에서 "system node show" 명령을 실행할 수 있습니다.  REST API를 사용하여 ONTAP 클러스터의 특성을 확인할 수도 있습니다.link:./rest/first-call.html["첫 번째 AFX 시스템 REST API 호출"] 자세한 내용은.

.AFX 스토리지 시스템은 언제부터 출시되었나요? AFX에서 지원되는 가장 초기의 ONTAP 버전은 무엇입니까?
AFX 스토리지 시스템은 2025년 10월 NetApp Insight 컨퍼런스에서 발표되었습니다. AFX는 ONTAP 9.17.1 및 이후 릴리스를 지원합니다. 자세한 내용은 NetApp 영업 담당자에게 문의하세요.

.AFX 저장 시스템의 맥락에서 "분산"이란 무엇을 의미합니까?
"분해된"이라는 용어는 문맥에 따라 AFX에서 두 가지 서로 다르지만 관련된 의미를 가질 수 있습니다.

우선적으로 고려해야 할 중요한 개념은 컨트롤러 노드의 컴퓨팅 기능을 스토리지 선반에서 분리하는 것입니다.  AFX를 사용하면 클러스터 컴퓨팅 및 스토리지 구성 요소가 Unified ONTAP 개성을 실행하는 FAS 및 AFF 시스템과 달리 더 이상 긴밀하게 결합되지 않습니다.  대신 클러스터 스위치를 통해 연결됩니다.  각 AFX 노드 컨트롤러는 전체 클러스터 스토리지 풀을 완벽하게 볼 수 있습니다.

분산형 스토리지와 관련된 두 번째 개념은 집계 및 RAID 관리가 관리 가능한 엔터티로서 제거된다는 것입니다.  AFX 내의 스토리지 추상화 계층은 물리적 디스크와 RAID 그룹을 포함한 스토리지의 하위 수준 측면을 자동으로 구성하고 관리합니다.  이를 통해 AFX 관리자는 볼륨과 버킷을 기반으로 한 고수준 스토리지 구성에 집중할 수 있습니다.



== 상호 운용성

.동일한 ONTAP 클러스터에서 AFX 시스템 노드를 AFF, ASA 또는 FAS 시스템 노드와 혼합할 수 있습니까?
아니요. 동일한 클러스터에서 서로 다른 ONTAP 특성을 실행하는 시스템 노드를 혼합할 수 없습니다. 예를 들어, 동일한 클러스터에서 AFX 노드(AFX ONTAP 개성을 실행)와 AFF 또는 FAS 노드(Unified ONTAP 개성을 실행)를 혼합할 수 없습니다.

.AFX 시스템 클러스터와 함께 FlexCache 사용할 수 있나요?
네. AFX 스토리지 시스템은 Unified ONTAP 특성을 실행하는 AFF 또는 FAS 시스템과의 FlexCache 지원합니다. 유일한 제한 사항은 쓰기 백업 모드가 있는 FlexCache AFX에서 지원되지 않는다는 것입니다.

.SnapMirror 또는 FlexCache 위해 AFX 시스템과 함께 Unified ONTAP 개성을 실행하는 AFF 또는 FAS 시스템을 사용하려면 어떤 ONTAP 버전이 필요합니까?
AFX의 SnapMirror 버전 규칙은 Unified ONTAP 과 동일합니다.  즉, Unified ONTAP 에서 복제하려면 소스 시스템이 지원되는 버전 범위 내에 있어야 합니다.  AFX에서 복제하려면 Unified ONTAP 시스템이 ONTAP 9.16.1 이상이어야 합니다(고급 용량 분산 기능이 지원되는 가장 초기 릴리스).  FlexCache 의 경우 소스 및 대상 시스템에 대해 설명된 것과 동일한 규칙이 적용됩니다. https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743"^] .

FlexGroup 볼륨에 대한 지원에는 몇 가지 차이점이 있습니다.  AFX의 FlexGroup 볼륨은 Writeback 모드를 사용하는 FlexCache 볼륨의 원본 볼륨이 될 수 없습니다.

.AFX 클러스터에 ONTAPI(ZAPI) API 호출을 할 수 있나요?
아니요. AFX에서는 ONTAP REST API만 지원됩니다.  ZAPI를 사용하는 모든 자동화 코드는 AFX와 함께 사용할 수 있도록 REST API로 변환해야 합니다.



== 고급 개념

.AFX 저장 시스템에서 지원되는 데이터 프로토콜은 무엇입니까?
AFX에서 지원하는 데이터 프로토콜은 다음과 같습니다.

* NFSv3, NFSv4.0, NFSv4.1, NFSv4.2
* SMB2.x, SMB3.x
* S3
* NDMP


.AFX에서는 데이터 프로토콜이 다르게 작동합니까?
아니요. AFX의 데이터 프로토콜은 AFF 및 FAS 시스템과 동일한 방식으로 작동합니다.

.AFX에서는 고급 디스크 파티셔닝(ADP)을 사용합니까?
아니요. ADP는 AFX와 함께 사용되지 않습니다.  AFX에는 루트 집계가 없으므로 디스크 공간 효율성을 극대화하는 데 ADP 기능이 필요하지 않습니다.

.AFX 스토리지 시스템의 백엔드 클러스터 네트워크에서 모든 유형의 스위치를 사용할 수 있나요?
아니요. AFX 스토리지 플랫폼에 대해 특별히 승인되어 함께 제공되는 스위치만 클러스터 네트워크에서 지원됩니다. 또한 이러한 백엔드 스위치는 AFX 클러스터 작업에 전용됩니다. 클라이언트 액세스 작업(NFS, SMB, S3 사용)은 프런트엔드 클라이언트 데이터 네트워크를 통해서만 수행해야 합니다.

.클러스터 스위치는 어떻게 구성되나요?
클러스터 네트워크 스위치는 NetApp 에서 제공하는 구성 파일을 사용하여 구성됩니다. 구성 파일의 변경은 지원되지 않습니다.

.AFX 클러스터의 스토리지는 어떻게 구성되나요?
AFX 클러스터에 연결된 모든 디스크와 스토리지 쉘프는 스토리지 가용성 영역(SAZ)의 일부입니다.  각 AFX 클러스터는 여러 AFX 클러스터에서 공유할 수 없는 SAZ를 하나만 지원합니다( SnapMirror 복제 및 FlexCache 작업 제외).

모든 노드는 SAZ의 모든 스토리지를 볼 수 있습니다.  클러스터에 스토리지 선반이 추가되면 ONTAP 자동으로 디스크를 추가합니다.

.AFX 클러스터에서 데이터는 어떻게 할당되나요?
데이터가 할당되면 SAZ의 모든 디스크에 배치될 수 있습니다.  데이터를 한 번 배치하면 더 이상 옮길 필요가 없습니다.  볼륨은 기본 데이터를 기반으로 생성되어 특정 노드에 할당됩니다.  볼륨은 일반적으로 밸런싱 프로세스의 일부로 AFX에 의해 이동될 수 있습니다.  이는 어느 노드의 NVRAM 쓰기 작업을 디스크에 커밋하는지에 영향을 미칩니다.  볼륨을 이동하면 볼륨을 소유하는 노드가 변경되지만 데이터 자체는 그대로 유지됩니다.

.AFX는 SAZ 전체의 거래량을 어떻게 관리하나요?
AFX에는 시스템과 사용자 개체 불균형에 대응하는 ATM(자동 토폴로지 관리)이라는 기능이 포함되어 있습니다.  ATM의 주요 목적은 AFX 클러스터 전반의 거래량을 균형 있게 조절하는 것입니다.  불균형이 감지되면 내부 작업이 트리거되어 활성 노드에 데이터를 균등하게 분산합니다.  데이터는 ZCVM을 사용하여 재할당되며, 객체 메타데이터만 복사하고 업데이트하면 됩니다.

.AFX 클러스터의 노드에 볼륨을 어떻게 배치합니까?
NetApp AFX는 클러스터의 모든 노드에 볼륨 배치를 자동으로 균형 있게 조정합니다.  ONTAP 9.18.1부터 볼륨을 배치하거나 이동할 때 노드의 성능을 고려하도록 배치 알고리즘이 향상되었습니다.  이를 통해 AFX 클러스터의 노드 전반에서 성능 균형이 향상되고 단일 노드가 과부하될 가능성이 훨씬 줄어듭니다.  이전 AFX 릴리스에서는 클러스터의 총 볼륨 수를 기준으로 배치가 결정되었습니다.  모든 노드에는 활동에 관계없이 동일한 수의 볼륨이 할당됩니다.

.AFX에서 볼륨 이동 작업은 AFF 나 FAS 시스템과 비교했을 때 어떻게 다르게 진행됩니까?
Unified ONTAP 특성을 실행하는 AFF 및 FAS 시스템을 사용하면 클러스터 내의 한 노드 또는 집계에서 다른 노드 또는 집계로 볼륨을 중단 없이 이전할 수 있습니다. 이 작업은 SnapMirror 기술을 사용한 백그라운드 복사 작업을 통해 수행됩니다.  대상 목적지에 새로운 대상 볼륨이 생성됩니다.  볼륨 크기와 클러스터 리소스 활용도에 따라 볼륨 이동 작업이 완료되는 데 걸리는 시간이 달라질 수 있습니다.

AFX에는 집계가 없습니다. 모든 스토리지는 클러스터의 모든 노드가 접근할 수 있는 단일 스토리지 가용성 영역(SAZ)에 포함됩니다. 결과적으로 볼륨 이동은 실제로 데이터를 복사할 필요가 없습니다.  대신 모든 볼륨 이동은 노드 간 포인터 업데이트를 통해 수행됩니다. 이를 ZCVM(Zero Copy Volume Move)이라고 하며, 실제로 데이터가 복사되거나 이동되지 않기 때문에 즉시 발생합니다. 이는 기본적으로 SnapMirror 복사 없이 Unified ONTAP 에서 사용되는 볼륨 이동 프로세스와 동일합니다.

최초 9.17.1 AFX 릴리스에서는 볼륨이 스토리지 장애 조치 복구 시나리오와 클러스터에서 노드가 추가되거나 제거될 때만 이동합니다. 이러한 움직임은 ONTAP 통해서만 제어됩니다.
