---
sidebar: sidebar 
permalink: protect-data/prepare-protect-data.html 
keywords: afx, afx system, prepare, prepare protect, prepare protect data 
summary: AFX 데이터를 보호하기 전에 몇 가지 주요 개념과 스토리지의 현재 상태를 숙지해야 합니다. 
---
= AFX 스토리지 시스템 데이터를 보호할 준비를 하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 데이터를 보호하기 전에 몇 가지 주요 개념과 기능에 대해 숙지해야 합니다.


TIP: AFF 및 FAS 시스템에서 사용할 수 있는 개념과 관리 절차 중 상당수가 AFX 스토리지 시스템에서도 동일하므로 Unified ONTAP 설명서를 검토하는 것이 도움이 될 수 있습니다.



== 용어 및 옵션

AFX 데이터 보호와 관련하여 알아야 할 용어가 몇 가지 있습니다.

스냅샷:: 스냅샷은 볼륨의 읽기 전용 특정 시점 이미지입니다.  이는 ONTAP의 복제 및 데이터 보호 서비스를 위한 기반 기술입니다.
일관성 그룹:: 일관성 그룹은 단일 단위로 관리되는 볼륨의 모음입니다.  일관성 그룹을 생성하면 애플리케이션 워크로드에 대한 스토리지 관리 및 데이터 보호를 간소화할 수 있습니다.  예를 들어, 개별 볼륨 대신 일관성 그룹을 사용하여 한 번의 작업으로 여러 볼륨의 스냅샷을 만들 수 있습니다.
계층적 일관성 그룹:: 계층적 일관성 그룹은 ONTAP 9.16.1에서 도입되었으며 AFX에서 사용할 수 있습니다.  계층적 구조를 사용하면 하나 이상의 일관성 그룹을 상위 그룹 아래의 자식 그룹으로 구성할 수 있습니다.  이러한 계층적 그룹을 사용하면 개별 스냅샷 정책을 자식 일관성 그룹에 적용하고 부모를 복제하여 모든 자식의 스냅샷을 단일 단위로 원격 클러스터에 복제할 수 있습니다.
SnapLock:: SnapLock 은 파일을 WORM(쓰기 한 번 읽기 여러 번) 상태로 옮겨서 보호할 수 있는 ONTAP 기능입니다.  이렇게 하면 지정된 보존 기간 동안 수정이나 삭제가 방지됩니다.  SnapLock 볼륨은 보존 기간을 기준으로 생성되며 생성 후에는 SnapLock 아닌 볼륨에서 변환할 수 없습니다.




== 관련 정보

* link:../administer/additional-ontap-svm.html["추가 AFX SVM 관리"]
* link:../get-started/prepare-cluster-admin.html["AFX 시스템 관리를 준비하세요"]

