---
sidebar: sidebar 
permalink: administer/additional-ontap-svm.html 
keywords: afx, afx system, additional administration, advanced administration 
summary: 일반적인 AFX SVM 관리 외에도 환경에 따라 수행해야 할 다른 작업이 있을 수 있습니다.  대부분의 추가 작업은 시스템 관리자를 사용하여 수행할 수 있지만, 어떤 경우에는 CLI를 사용해야 할 수도 있습니다. 
---
= AFX 스토리지 시스템 SVM에 대한 추가 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반적인 AFX SVM 관리 외에도 환경에 따라 수행해야 할 다른 작업이 있을 수 있습니다.  대부분의 추가 작업은 시스템 관리자를 사용하여 수행할 수 있지만, 어떤 경우에는 CLI를 사용해야 할 수도 있습니다.


NOTE: 설명된 ONTAP 기능과 관리 방식은 AFX 스토리지 시스템과 Unified ONTAP 실행하는 AFF 또는 FAS 시스템에서 공통적입니다.  해당 Unified ONTAP 문서에 대한 링크가 적절하게 포함되어 있습니다.



== 스토리지 관리 및 성능

AFX 배포와 함께 구성하고 사용할 수 있는 몇 가지 선택적 스토리지 관리 및 성능 기능이 있습니다.



=== ONTAP NAS 스토리지 관리

네트워크 연결 스토리지(NAS)는 네트워크의 여러 클라이언트가 액세스할 수 있는 전용 파일 스토리지를 제공합니다.  ONTAP 여러 NAS 프로토콜을 지원합니다. 참조하다 https://docs.netapp.com/us-en/ontap/nas-management/index.html["NAS 스토리지 관리"^] 자세한 내용은.



=== ONTAP FlexCache 볼륨

FlexCache 는 ONTAP 원격 캐싱 기능입니다.  이를 통해 데이터를 클라이언트에게 더 가까이 전달하여 액세스 성능을 개선하고 비용을 절감할 수 있습니다.  원래 파일 시스템의 메타데이터만 처음에 복사하는 FlexCache 볼륨을 생성하면 파일 배포가 간소화되고 WAN 트래픽이 줄어듭니다. 참조하다 https://docs.netapp.com/us-en/ontap/flexcache/index.html["ONTAP FlexCache 볼륨에 대해 알아보세요"^] 자세한 내용은.



=== ONTAP FlexGroup 볼륨

FlexGroup 볼륨은 트래픽을 자동적이고 투명하게 공유하는 여러 멤버 볼륨으로 구성됩니다.  FlexGroup 볼륨은 높은 성능과 간소화된 관리를 포함한 여러 가지 이점을 제공합니다. 참조하다 https://docs.netapp.com/us-en/ontap/flexgroup/creation-workflow-task.html["FlexGroup 볼륨 설정"^] 자세한 내용은.



== 데이터 보호

AFX 배포와 함께 구성하고 사용할 수 있는 선택적 데이터 보호 기능이 여러 가지 있습니다.



=== 일관성 그룹

일관성 그룹은 단일 단위로 관리되는 볼륨의 모음입니다. 참조하다 https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["ONTAP 일관성 그룹에 대해 알아보세요"^] 자세한 내용은.



=== SnapLock

볼륨 수준에서 파일을 WORM(Write Once Read Many) 상태로 변환하여 파일을 보호할 수 있습니다.  SnapLock 두 가지 모드를 지원합니다.  규정 준수 모드는 정부 또는 업계별 요구 사항을 충족하는 보존 기간이 만료될 때까지 파일을 삭제할 수 없도록 보장합니다.  엔터프라이즈 모드에서는 권한이 있는 사용자가 보존 기간이 만료되기 전에 파일을 삭제할 수 있습니다. 참조하다 https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLock 에 대해 알아보세요"^] 자세한 내용은.



== ONTAP 이벤트 및 성능 모니터링

클러스터의 상태와 성능을 모니터링할 수 있습니다.  여기에는 이벤트에 대한 알림 설정과 시스템 상태 알림에 대한 알림 관리가 포함됩니다.  참조하다 https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html["이벤트, 성능 및 상태 모니터링"^] 더 많은 정보를 원하시면



== 관련 정보

* link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"]
* link:../administer/additional-ontap-cluster.html["AFX 클러스터에 대한 추가 관리"]

