---
sidebar: sidebar 
permalink: administer/migrate-svm.html 
keywords: afx, afx system, svm, migrate svm 
summary: 데이터 SVM을 한 ONTAP 클러스터에서 다른 ONTAP 클러스터로 마이그레이션할 수 있습니다.  AFX를 사용한 SVM 마이그레이션은 Unified ONTAP 과 동일하게 작동하지만 상호 운용성 고려 사항이 몇 가지 있습니다.  SVM 마이그레이션 수행에 대한 자세한 내용은 Unified ONTAP 설명서를 참조하세요. 
---
= AFX 스토리지 시스템 SVM 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 SVM을 한 ONTAP 클러스터에서 다른 ONTAP 클러스터로 마이그레이션할 수 있습니다.  AFX를 사용한 SVM 마이그레이션은 Unified ONTAP 과 동일하게 작동하지만 상호 운용성 고려 사항이 몇 가지 있습니다.  SVM 마이그레이션 수행에 대한 자세한 내용은 제공된 Unified ONTAP 설명서를 참조하세요.



== 상호 운용성 고려 사항

SVM 마이그레이션을 계획하고 수행하기 전에 기능과 제한 사항을 포함한 상호 운용성 고려 사항을 알아야 합니다.



=== 사용 사례

클러스터 관리자는 SVM을 소스 클러스터에서 대상 클러스터로 다시 이동할 수 있습니다.  용량 관리 및 부하 분산의 일환으로 이를 수행할 수도 있고, 장비 업그레이드나 데이터 센터 통합을 허용하기 위해 이를 수행할 수도 있습니다.

AFX 스토리지 시스템은 Unified ONTAP 에서의 기존 업그레이드를 지원하지 않으므로 SVM 마이그레이션은 중요한 사용 사례입니다.  중단 없이 Unified ONTAP9 클러스터에서 AFX 클러스터로 애플리케이션 워크로드를 이동할 수 있습니다.  또한 SVM은 AFX 클러스터에서 Unified ONTAP 클러스터로, AFX 클러스터 간에 마이그레이션하는 등 다른 방법으로도 마이그레이션할 수 있습니다.



=== 버전 상호 운용성

다음 표에서는 ONTAP 특성과 소스 및 대상 클러스터의 릴리스에 따라 허용되는 SVM 마이그레이션을 설명합니다.

[cols="40,30,30"]
|===
| 방향 | 소스 버전 | 목적지 버전 


| AFX로 통합 | 9.15.1 - 9.17.1 | 9.17.1 


| AFX에서 Unified로 | 9.17.1 | 9.17.1 


| AFX에서 AFX로 | 9.17.1 | 9.17.1 
|===


=== 사전 점검

Unified ONTAP 에는 AFX로 구현된 여러 가지 사전 검사 기능이 포함되어 있습니다.  또한, AFX에서 지원되지 않는 플래그 기능에는 다음과 같은 몇 가지 새로운 사전 검사가 추가되었습니다.

* FabricPool (복합 집합체에 있는 볼륨)
* 두꺼운 프로비저닝 볼륨




=== 볼륨 프로비저닝

AFX 볼륨은 클러스터의 SAZ(스토리지 가용성 영역) 전체에 걸쳐 배치를 균형 있게 조정하기 위해 프로비저닝됩니다.

공간 보장:: AFX는 두꺼운 프로비저닝을 지원하지 않습니다.  사전 검사는 마이그레이션 중인 SVM의 볼륨이 두꺼운 프로비저닝된 경우 마이그레이션이 실패하도록 하는 데 사용됩니다.
암호화:: AFX 시스템은 NetApp 볼륨 암호화(NVE)는 지원하지만 NetApp 집계 암호화(NAE)는 지원하지 않습니다.  이로 인해 Unified ONTAP 클러스터의 모든 NAE 볼륨은 AFX로 마이그레이션될 때 NVE 볼륨으로 변환됩니다.  다음 표는 호환성과 변환을 요약한 것입니다.


[cols="50,50"]
|===
| 소스 볼륨 | 목적지 볼륨 


| 일반 텍스트 | 일반 텍스트 


| NVE | NVE 


| NAE | NVE 
|===


== 관련 정보

* https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["ONTAP SVM 데이터 이동성"^]
* link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"]

