---
sidebar: sidebar 
permalink: administer/remove-nodes.html 
keywords: netapp afx, remove node, unjoin, cluster remove-node, evacuate volumes, zero-copy volume move 
summary: NetApp AFX 클러스터에서 볼륨 마이그레이션, LIF 마이그레이션 및 HA 파트너 연결 해제를 포함하여 스토리지 노드를 제거하는 방법을 알아보십시오. 
---
= AFX 스토리지 시스템 클러스터에서 노드 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
유지 관리 또는 하드웨어 교체를 위해 AFX 클러스터에서 노드를 제거해야 할 수 있습니다. 한 번에 하나의 노드만 제거할 수 있으며, 노드를 제거한 후에는 해당 노드의 HA 파트너도 함께 제거해야 합니다.

.이 작업에 관하여
* AFX 스토리지 시스템에서는 모든 스토리지가 클러스터의 모든 노드에서 접근 가능한 단일 스토리지 가용 영역(SAZ) 내에 저장됩니다. 따라서 노드가 제거될 때, 제거되는 노드의 데이터를 복사할 필요가 없습니다. 대신, 나머지 노드들 간에 제거되는 노드의 볼륨에 대한 포인터가 업데이트됩니다. 이를 Zero Copy Volume Move(ZCVM)라고 하며, 실제로 데이터가 복사되거나 이동되지 않기 때문에 즉시 처리됩니다.
+
[NOTE]
====
노드를 제거하기 전에 ZCVM에서 이동할 수 없는 볼륨은 수동으로 처리해야 합니다. 여기에는 볼륨 복제본, 오프라인 볼륨, 원래 암호화 키가 변경되었거나 재설정된 암호화된 볼륨, SnapMirror 클라우드를 사용하여 복원된 볼륨이 포함됩니다. 감사 스테이징 볼륨과 루트 볼륨은 노드 연결 해제 프로세스 중에 ZCVM에서 이동합니다.

** link:https://docs.netapp.com/us-en/ontap/nas-audit/basic-auditing-concept.html["감사 스테이징 볼륨"^]에 대해 자세히 알아보십시오.
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/rekey-encrypted-volume-task.html["재입력된 암호화 볼륨"^]에 대해 자세히 알아보십시오.


====
* 노드를 클러스터에서 성공적으로 분리하면 다음과 같은 작업이 수행됩니다.
+
** 노드를 부적격으로 표시하고 CLAM 쿼럼에서 제외합니다.
** 노드를 깔끔하게 종료하고 소유권을 살아남은 노드로 이전합니다.
** 노드의 RAID 고가용성(HA) 상태를 정리하고 클러스터 데이터베이스에서 해당 상태를 삭제합니다.






[[step-1-prepare-to-remove-nodes-from-an-afx-cluster]]
== 1단계: AFX 클러스터에서 노드를 제거할 준비를 합니다.

AFX 클러스터에서 노드를 제거하기 전에 클러스터가 정상인지, 그리고 제거할 노드에 데이터 LIF가 없는지 확인해야 합니다.

.단계
. 클러스터가 정상인지 확인하십시오.
+
[source, cli]
----
cluster show
----
. 제거하려는 노드가 온라인 상태이고 정상 작동하는지 확인하십시오.
+
[source, cli]
----
system node show -node <node> -health -epsilon
----
. 노드의 LIF를 확인합니다.
+
[source, cli]
----
network interface show -curr-node <node>
----
. 노드에서 데이터 LIF를 마이그레이션합니다.
+
[source, cli]
----
network interface migrate -vserver <SVM> -lif <LIF> -dest-node <destination_node> -dest-port <destination_port>
----
+
모든 데이터 LIF에 대해 이 명령을 반복하십시오. 클러스터 LIF와 노드 관리 LIF만 노드에 남아 있어야 합니다.

. 노드에 모든 데이터 LIF가 제거되었고 클러스터 LIF와 노드 관리 LIF만 남아 있는지 확인하십시오.
+
[source, cli]
----
network interface show -curr-node <node>
----


.다음 단계는 무엇입니까?
준비 단계를 완료한 후에는 HA 쌍의 첫 번째 노드를 클러스터에서 제거한 다음 해당 HA 파트너를 제거할 수 있습니다.



[[step-2-unjoin-a-single-node-from-an-afx-cluster]]
== 2단계: AFX 클러스터에서 단일 노드 분리

AFX 클러스터에서 노드를 제거하려면 먼저 노드 제거를 위한 준비 단계를 완료해야 합니다. 클러스터에서 노드를 제거한 후에는 해당 노드의 HA 파트너도 제거해야 합니다.

.시작하기 전에
link:manage-autosupport.html["AutoSupport 메시지를 발행합니다"]하여 클러스터에서 노드를 제거하고 있음을 NetApp 기술 지원에 알리는 것이 좋습니다.

.단계
. 노드 볼륨을 비우십시오:
+
[source, cli]
----
system node evacuate-volumes start -node <node_to_remove>
----
. 노드 볼륨이 비워졌는지 확인하십시오.
+
[source, cli]
----
system node evacuate-volumes show -node <node_to_remove>
----
+
진행하기 전에 *대기 중인 카운트*가 0이 될 때까지 기다리십시오. 볼륨이 완전히 비워질 때까지 엡실론이나 적격성을 이동하지 마십시오.

+
필요한 경우  `system node evacuate-volumes abort -node <node>` 명령을 사용하여 대피 프로세스를 중단할 수 있습니다.

. 엡실론을 보유한 노드를 확인합니다.
+
[source, cli]
----
cluster show -epsilon true
----
+
.. 제거하려는 노드에 엡실론이 있는 경우, 엡실론을 다른 노드로 이동하십시오.
+
[source, cli]
----
cluster modify -node <surviving_node> -epsilon true
----


. 현재 기본 노드를 식별하십시오.
+
[source, cli]
----
cluster ring show
----
+
.. 제거하려는 노드가 현재 기본 노드인 경우, 해당 노드를 부적격 상태로 만드십시오.
+
[source, cli]
----
cluster modify -node <node_to_remove> -eligibility false
----


. 나머지 데이터 LIF의 홈 노드를 표시합니다.
+
[source, cli]
----
network interface show -home-node <node_to_remove>
----
. 나머지 데이터 LIF의 홈 노드를 다른 노드로 변경합니다.
+
[source, cli]
----
network interface modify -vserver <SVM> -lif <LIF> -home-node <surviving_node>
----
+
클러스터 LIF와 노드 관리 LIF는 나가는 노드에 남겨두십시오.

. 제거할 노드의 인수 기능을 비활성화합니다.
+
[source, cli]
----
storage failover modify -node <node_to_remove> -enable-takeover-of false
----
. 제거할 노드에 대해 테이크오버가 비활성화되어 있는지 확인하십시오.
+
[source, cli]
----
storage failover show
----
+
페일오버가 비활성화된 경우 HA 쌍에서 테이크오버가 불가능합니다.

. 정상적으로 작동하는 노드에서 권한 수준을 고급으로 설정하십시오.
+
[source, cli]
----
privilege set -level advanced
----
. 클러스터에서 노드를 분리합니다.
+
[source, cli]
----
cluster remove-node -node <node_to_remove>
----
+
경고 메시지를 확인하십시오. 작업이 완료되면 *Node remove succeeded* 메시지가 표시되어야 합니다.



.다음은 무엇인가요?
이전 단계를 반복하여 클러스터에서 HA 파트너를 제거하십시오. 연결되지 않은 노드의 HA 파트너가 제거될 때까지는 추가 노드를 제거할 수 없습니다.



[[step-3-optionally-clean-the-removed-hardware]]
== 3단계: (선택 사항) 제거한 하드웨어 청소

클러스터에서 제거한 노드를 다른 용도로 사용하려면 해당 노드의 구성을 지우고 모든 디스크를 초기화해야 클러스터에 다시 참여할 수 있습니다.

.단계
. 부팅 과정 중 메시지가 나타나면 Ctrl-C를 눌러 부팅 메뉴를 표시합니다.
. 부팅 메뉴 옵션 *(4) Clean configuration and initialize all disks*를 선택합니다.


.다음은 무엇인가요?
해당  `cluster add-node` 명령을 사용하면 동일한 클러스터 내에서 HA 쌍을 재사용할 수 있습니다.
