---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: afx, afx system, upgrade, upgrade ontap 
summary: AFX 시스템에서 ONTAP 소프트웨어를 업그레이드하면 비용 절감, 중요 작업 부하 가속화, 보안 강화, 조직에서 사용할 수 있는 데이터 보호 범위 확장에 도움이 되는 새롭고 향상된 ONTAP 기능을 활용할 수 있습니다. 
---
= AFX 스토리지 시스템에서 ONTAP 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 시스템에서 ONTAP 소프트웨어를 업그레이드하면 비용 절감, 중요 작업 부하 가속화, 보안 강화, 조직에서 사용할 수 있는 데이터 보호 범위 확장에 도움이 되는 새롭고 향상된 ONTAP 기능을 활용할 수 있습니다.


CAUTION: AFX 스토리지 시스템은 지원하지 않습니다 link:../administer/revert-ontap.html["ONTAP 되돌리기"] 운영.

AFX 스토리지 시스템을 위한 ONTAP 소프트웨어 업그레이드는 다른 ONTAP 시스템을 위한 업그레이드와 동일한 프로세스를 따릅니다.  Active IQ Digital Advisor ( Digital Advisor 라고도 함)에 대한 활성 SupportEdge 계약이 있는 경우 다음을 수행해야 합니다.link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["업그레이드 어드바이저로 업그레이드 준비"^] .  업그레이드 어드바이저는 클러스터를 평가하고 구성에 맞는 업그레이드 계획을 만들어 불확실성과 위험을 최소화하는 데 도움이 되는 인텔리전스를 제공합니다.  Active IQ Digital Advisor 에 대한 활성 SupportEdge 계약이 없는 경우 다음을 수행해야 합니다.link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html["업그레이드 어드바이저 없이 업그레이드 준비"^] .

업그레이드를 준비한 후에는 다음을 사용하여 업그레이드를 수행하는 것이 좋습니다.link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["System Manager에서 자동화된 비중단 업그레이드(ANDU)"] .  ANDU는 ONTAP의 고가용성(HA) 장애 조치 기술을 활용하여 업그레이드 중에도 클러스터가 중단 없이 데이터를 계속 제공할 수 있도록 보장합니다.

.관련 정보
* https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP 업그레이드에 대해 알아보세요"^] .




[[execute-automated-pre-upgrade-checks-before-a-planned-upgrade]]
== 계획된 업그레이드 전에 자동화된 사전 업그레이드 검사를 실행합니다

ONTAP 소프트웨어를 업그레이드하는 과정에 있지 않아도 ONTAP 자동 업그레이드 사전 점검을 실행할 수 있습니다. ONTAP 자동 업그레이드 프로세스와 별도로 업그레이드 전 점검을 실행하면 클러스터에 대해 수행되는 점검 항목을 확인할 수 있으며 실제 업그레이드를 시작하기 전에 수정해야 할 오류 또는 경고 목록을 제공받을 수 있습니다.

ONTAP 9.19.1부터 오류와 경고가 별도로 표시되어 업그레이드 전에 해결해야 할 문제를 쉽게 식별할 수 있습니다.

link:https://docs.netapp.com/us-en/ontap/upgrade/automated-pre-checks.html["ONTAP 자동 업그레이드 전 검사 실행 방법을 알아보세요."^].
