---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'NetApp AFX 시스템은 AFF 및 FAS 스토리지에서 실행되는 ONTAP 특성(Unified ONTAP 이라고 함)과 다른 맞춤형 ONTAP 특성을 실행합니다.  AFX 시스템이 FAS 및 AFF 시스템과 어떻게 유사하고 어떻게 다른지 알아야 합니다.  이는 귀중한 관점을 제공하며 사용자 환경에 AFX를 배포할 때 도움이 될 수 있습니다.' 
---
= AFX 저장 시스템을 AFF 및 FAS 시스템과 비교
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 시스템은 AFF 및 FAS 스토리지에서 실행되는 ONTAP 특성(Unified ONTAP 이라고 함)과 다른 맞춤형 ONTAP 특성을 실행합니다.  AFX 시스템이 FAS 및 AFF 시스템과 어떻게 유사하고 어떻게 다른지 알아야 합니다.  이는 귀중한 관점을 제공하며 사용자 환경에 AFX를 배포할 때 도움이 될 수 있습니다.


TIP: AFX 설명서에는 ONTAP 특성에 관계없이 동일하게 동작하는 기능에 대한 자세한 내용을 제공하는 Unified ONTAP 문서 사이트의 다양한 항목에 대한 링크가 포함되어 있습니다.  추가 콘텐츠는 AFX 스토리지 시스템을 관리할 때 도움이 될 수 있는 보다 자세한 내용을 제공합니다.



== 구성 차이점

AFX 구성은 AFF 및 FAS 시스템과 몇 가지 측면에서 다릅니다.

고급 용량 밸런싱:: 고급 용량 균형 기능은 다음을 사용하여 제어됩니다. `-gdd` CLI 매개변수는 모든 FlexGroup 볼륨에 대해 기본적으로 활성화됩니다.




== 지원되지 않거나 제한된 Unified ONTAP 기능

NetApp AFX는 고성능 NAS 및 개체 워크로드에 최적화되어 있습니다.  이 때문에 AFF 와 FAS 는 물론 다른 Unified ONTAP 스토리지 시스템에도 차이점이 있습니다.  다음 기능은 NetApp AFX에서 사용할 수 없습니다. 목록은 주요 기능 또는 기능 영역별로 구성되어 있습니다.  AFX에 대한 업데이트 및 변경 사항도 검토해야 합니다.link:../release-notes/whats-new-9171.html["새로운 소식"] 귀하의 석방을 기준으로 합니다.



=== 블록 및 SAN

* SAN 관리 및 클라이언트 액세스
* LUN 및 NVMe 네임스페이스
* 볼륨의 두꺼운 프로비저닝




=== 집계 및 물리적 저장소

* MetroCluster
* 물리적 노드 소유 집계
* RAID 관리
* NetApp 집계 암호화(NAE)
* 집계 수준 중복 제거
* SyncMirror (집계 미러링)
* FabricPool 계층화




=== 데이터 복제(SnapMirror)


NOTE: Unified ONTAP 과 AFX 간의 모든 데이터 복제는 동일한 버전 제한 사항을 사용하여 양방향으로 지원됩니다. https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror 관계에 대한 호환 ONTAP 버전"^] (몇 가지 사소한 예외가 있음).

* LUN 또는 NVMe 네임스페이스를 포함하는 AFF 또는 FAS 시스템에서 볼륨 복제가 없습니다.
* FlexGroup 볼륨은 고급 용량 밸런싱이 필요하기 때문에 AFX에서 Unified ONTAP 버전 9.16.1 이상으로만 복제할 수 있습니다.




=== 관리 용이성

* ONTAPI API(ZAPI)
* 지원되지 않는 기능(예: MetroCluster)에 대한 REST API
* 성능 통계를 위한 REST API의 몇 가지 초기 제한 사항
* AIQ Unified Manager 지원
* Grafana Harvest 버전 25.08.1 이상
* NetApp Trident 버전 25.10 이상




== 명령줄 인터페이스 변경 사항

AFX에서 사용할 수 있는 ONTAP CLI는 일반적으로 AFF 및 FAS 시스템에서 사용할 수 있는 CLI를 반영합니다.  하지만 다음과 같은 몇 가지 차이점이 있습니다.

* 다음과 관련된 새로운 AFX 명령:
+
** 저장 가용성 영역의 용량 표시
** 부트 미디어


* SAN 관련 명령 없음
* 집계 관리 명령이 더 이상 필요하지 않습니다.
* 집계 표시에 이제 전체 스토리지 가용성 영역(SAZ)이 표시됩니다.




== 관련 정보

* link:../get-started/system-design.html["AFX 시스템 특성"]
* link:../get-started/software-architecture.html["AFX 아키텍처의 세부 사항"]
* link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"]
* link:../administer/additional-ontap-cluster.html["추가 AFX 클러스터 관리"]
* link:../administer/additional-ontap-svm.html["추가 AFX SVM 관리"]

