---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX 스토리지 시스템은 ONTAP 스토리지 모델을 분산형 고성능 NAS 솔루션으로 발전시킨 차세대 스토리지 아키텍처를 기반으로 합니다.  AFX는 매우 높은 성능을 제공하는 고급 기술과 처리 기법을 통해 파일 및 개체 워크로드를 모두 지원합니다. 
---
= AFX 스토리지 시스템에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 스토리지 시스템은 ONTAP 스토리지 모델을 분산형 고성능 NAS 솔루션으로 발전시킨 차세대 스토리지 아키텍처를 기반으로 합니다.  AFX는 매우 높은 성능을 제공하는 고급 기술과 처리 기법을 통해 파일 및 개체 워크로드를 모두 지원합니다.



== 일반적인 애플리케이션 워크로드

NetApp AFX 스토리지 시스템은 높은 성능과 독립적인 확장성을 요구하는 NAS 및 S3 개체 워크로드의 고유한 요구 사항을 충족합니다.  이러한 애플리케이션은 높은 동시성과 병렬 I/O를 기반으로 구축된 고급 디자인의 이점을 누리고 있습니다.  AFX는 다음을 포함하여 여러 유형의 애플리케이션 워크로드를 배포하고 관리하는 조직에 이상적입니다.

* 지속적으로 높은 대역폭과 방대한 데이터 세트에 대한 액세스가 필요한 딥 러닝과 관련된 학습 및 반복적 모델 개선.
* 텍스트, 이미지, 비디오를 포함한 다양한 데이터 유형을 처리합니다.
* 엄격한 응답 시간 창이 필요한 저지연 실시간 추론 애플리케이션입니다.
* 데이터 엔지니어와 데이터 과학자가 셀프 서비스 데이터 관리를 통해 이점을 얻을 수 있는 데이터 과학 및 머신 러닝 파이프라인입니다.




== 시스템 설계 특성

AFX 시스템은 고성능 NAS 플랫폼으로 작동할 수 있도록 하는 여러 가지 설계 특성을 갖추고 있습니다.

스토리지와 컴퓨팅 기능 분리:: 다른 NetApp ONTAP 스토리지 시스템과 달리 AFX 클러스터의 컴퓨팅 및 스토리지 요소는 분리되어 있으며 스위치드 네트워크를 통해 결합되어 있습니다.  디스크 소유권이 더 이상 특정 노드에 구속되지 않아 여러 가지 이점이 있습니다.  예를 들어, AFX 클러스터의 컴퓨팅 및 스토리지 구성 요소는 독립적으로 확장될 수 있습니다.
자동화된 스토리지 관리:: AFX 스토리지 관리자는 더 이상 물리적 집계를 사용할 수 없습니다.  대신 AFX는 클러스터에 새로운 스토리지 선반이 추가되면 노드에 대한 가상 용량 할당과 RAID 그룹 구성을 자동으로 관리합니다.  이러한 설계는 관리를 간소화하고 비전문가에게도 데이터를 관리할 수 있는 기회를 제공합니다.
클러스터를 위한 단일 스토리지 풀:: 스토리지 노드와 쉘프는 NetApp AFX와 분리되어 있으므로 클러스터의 모든 스토리지 용량은 SAZ(스토리지 가용성 영역)라는 단일 풀에 수집됩니다.  SAZ의 디스크와 셸프는 AFX 클러스터의 모든 스토리지 노드에서 읽기 및 쓰기 작업을 위해 사용할 수 있습니다.  또한, 모든 클러스터 노드는 장애 발생 시 디스크 재구축에 참여할 수 있습니다. 참조하다link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"] 자세한 내용은.
고성능:: NetApp AFX는 매우 낮은 지연 시간과 높고 지속적인 대역폭을 제공하므로 고성능 NAS 및 개체 작업 부하에 맞게 설계되었습니다.  AFX는 고유한 아키텍처를 통해 디스크에 대한 노드의 높은 비율을 처리할 수 있는 최신 하드웨어와 스토리지 선반을 사용합니다.  일반적인 1:1(노드:셸프) 비율을 넘어 스토리지 노드를 확장하면 디스크의 에지 한계까지 가능한 성능 프로필이 극대화됩니다.  이 디자인은 가장 중요한 애플리케이션에 효율성과 저장 밀도를 제공합니다.
독립적이고 대규모:: 분리된 스토리지 노드와 셸프를 기반으로 AFX 클러스터는 애플리케이션 요구 사항에 따라 독립적이고 중단 없이 확장될 수 있습니다.  CPU와 처리량을 늘리려면 스토리지 노드를 추가하고, 스토리지 용량과 디스크 성능을 늘리려면 쉘프를 추가할 수 있습니다.  NetApp AFX 아키텍처는 클러스터의 최대 크기에 대한 새로운 가능성을 제공합니다.  ONTAP 릴리스를 기반으로 한 AFX 클러스터의 최신 제한 사항은 NetApp Hardware Universe 참조하세요.
제로 복사 데이터 이동성:: NAS 및 개체 클라이언트는 ONTAP 클러스터의 볼륨에 액세스합니다.  중단 없이 노드 전체에 볼륨을 재배치하여 용량 및 성능 균형 목표를 달성할 수 있습니다.  Unified ONTAP 사용하면 SnapMirror 기술을 사용하여 볼륨을 이동하는데, 이 과정에서 시간이 걸리고 임시 용량이 추가로 필요할 수 있습니다.  하지만 AFX를 사용하면 공유 스토리지 가용성 영역(SAZ) 내에서 데이터 복사 작업이 더 이상 필요하지 않습니다.  대신 볼륨 메타데이터만 이동하므로 성능이 크게 향상됩니다. 참조하다link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"] 자세한 내용은.
향상된 HA 기능:: NetApp AFX는 고가용성(HA) 구성 및 처리를 위한 다양한 개선 사항을 제공합니다.  AFX를 사용하면 HA 파트너 노드를 직접 연결할 필요가 없으며 대신 HA 쌍이 내부 클러스터 네트워크를 통해 통신할 수 있습니다.  이 설계는 관리자에게 데이터 센터의 별도 랙이나 행에 HA 쌍을 배포하여 장애 허용성을 강화하는 옵션을 제공합니다.  또한 AFX의 제로 복사 모빌리티는 HA 장애 조치 시나리오까지 확장됩니다.  노드에 장애가 발생하면 해당 볼륨은 HA 파트너로 장애 조치되어 남아 있는 모든 쓰기 작업을 디스크에 커밋합니다.  그런 다음 ONTAP 클러스터의 모든 남은 노드에 볼륨을 균등하게 분산합니다.  즉, 데이터 배치를 처음 설계할 때 스토리지 장애 조치 성능을 더 이상 고려할 필요가 없습니다.




== 하드웨어 인프라

NetApp AFX 스토리지 시스템은 고성능 NAS 고객의 요구 사항에 맞춰 간소화된 환경을 만드는 통합 하드웨어 및 소프트웨어 솔루션을 제공합니다.


TIP: 당신은 검토해야합니다link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"] 하드웨어 상호 운용성 및 업그레이드 옵션에 대한 자세한 내용은 여기를 참조하세요.

AFX 클러스터에는 다음 하드웨어 구성 요소가 사용됩니다.

* AFX 1K 컨트롤러
* NX224 선반
* Cisco Nexus 9332D-GX2B 또는 Nexus 9364D-GX2A 스위치




== 관련 정보

* https://hwu.netapp.com/["NetApp Hardware Universe"^]
* https://www.netapp.com/afx/["NetApp AFX"^]

