---
sidebar: sidebar 
permalink: get-started/system-design.html 
keywords: afx, afx system, characteristics, design 
summary: NetApp AFX 스토리지 시스템은 고성능 NAS 플랫폼으로 작동할 수 있도록 하는 여러 가지 특성을 갖추고 있습니다. 
---
= AFX 저장 시스템 특성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 스토리지 시스템은 고성능 NAS 플랫폼으로 작동할 수 있도록 하는 여러 가지 특성을 갖추고 있습니다.

스토리지와 컴퓨팅 기능 분리:: AFF 및 FAS 스토리지 시스템과 달리 클러스터의 AFX 스토리지 및 컴퓨팅 요소는 분리되어 있습니다.  AFX 컨트롤러는 제한된 로컬 디스크 세트에만 액세스할 수 없습니다.
집계 및 RAID 관리 제거:: 스토리지 관리자는 더 이상 집계 및 RAID 그룹을 관리할 필요가 없습니다.  AFX는 이러한 작업을 처리하여 관리를 간소화하고 비전문가도 데이터를 관리할 수 있는 기회를 제공합니다.
클러스터를 위한 단일 스토리지 풀:: AFX 컴퓨팅과 스토리지를 분리하고 스토리지 관리를 간소화하면 단일 스토리지 풀이 생성됩니다.  이 스토리지 가용성 영역(SAZ)은 AFX 클러스터의 모든 컨트롤러 노드에서 사용할 수 있습니다. 보다link:../faq-ontap-afx.html["AFX 스토리지 시스템에 대한 FAQ"] 자세한 내용은.
고성능:: AFX는 특수 AI/ML 애플리케이션에 필요한 고성능을 위해 제작되었습니다.  최신 하드웨어를 보다 효율적으로 활용하여 매우 낮은 지연 시간과 높고 지속적인 대역폭을 제공할 수 있습니다.
운영의 단순성:: 단일 스토리지 풀은 자동 스토리지 관리를 포함한 다른 기능과 함께 훨씬 더 간단한 관리 및 운영 모델을 제공합니다.
확장성:: 클러스터 내의 컨트롤러 노드와 스토리지 선반 세트는 애플리케이션 요구 사항에 따라 독립적으로 확장될 수 있습니다.  컨트롤러나 선반을 추가할 때는 관리 요구 사항과 중단이 제한적입니다.
향상된 데이터 이동성:: 실제로 데이터를 복사하지 않고도 볼륨을 클러스터 컨트롤러 노드 간에 중단 없이 이동할 수 있습니다.  대신 메타데이터 디렉토리와 인덱스 포인터가 업데이트됩니다.  이를 통해 일반적인 관리 절차의 성능은 물론, 장애 발생 시 복구 성능도 크게 향상됩니다.

