---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: AFX 스토리지 시스템에서 사용할 수 있는 ONTAP 9.18.1의 새로운 기능에 대해 알아보세요. 
---
= AFX 스토리지 시스템용 ONTAP 9.18.1의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFX 스토리지 시스템에서 사용할 수 있는 ONTAP 9.18.1의 새로운 기능에 대해 알아보세요.


NOTE: ONTAP 9.18.1에는 AFX에서 사용할 수 있는 여러 가지 새로운 기능이 있습니다. 이러한 기능 중 일부는 AFX에 특화된 기능이며, 다른 많은 기능은 공통으로 사용되는 제품 기반에서 파생된 것입니다. 아래에 설명된 AFX 기능을 검토하는 것 외에도 https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9181.html["ONTAP 9.18.1의 새로운 기능"^]을 참조하십시오.



[[security]]
== 보안

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
xref:../administer/additional-ontap-cluster.html[추가 관리: IPsec 하드웨어 오프로드]
 a| 
IPsec 하드웨어 오프로드 지원이 IPv6까지 확장되었습니다.



 a| 
xref:../administer/additional-ontap-cluster.html[추가 관리: OpenSSL PQC 알고리즘]
 a| 
ONTAP는 SSL에 대한 포스트 양자 컴퓨팅 암호화 알고리즘을 지원합니다. 이러한 알고리즘은 향후 발생할 수 있는 양자 컴퓨팅 공격에 대한 추가적인 보호 기능을 제공하며, SSL FIPS 모드가 비활성화된 경우에 사용할 수 있습니다.

|===


[[storage-resource-management-enhancements]]
== 스토리지 리소스 관리 향상

[cols="2,4"]
|===
| 업데이트 | 설명 


| 향상된 볼륨 배치  a| 
NetApp AFX는 클러스터의 모든 노드에 볼륨 배치를 자동으로 균형 있게 조정합니다.  이전 ONTAP 릴리스에서는 배치 알고리즘이 클러스터의 볼륨 수를 기반으로 했습니다.  모든 노드에는 활동에 관계없이 동일한 수의 볼륨이 할당됩니다.  ONTAP 9.18.1부터 볼륨을 배치하거나 이동할 때 노드의 성능을 고려하도록 알고리즘이 향상되었습니다.  이를 통해 AFX 클러스터의 노드 전반에서 성능 균형이 향상되고 단일 노드가 과부하될 가능성이 훨씬 줄어듭니다.



 a| 
xref:../administer/configure-svm.html[SVM 및 볼륨에 대한 2단계 중첩 QoS 정책 그룹 지원]
 a| 
SVM에 QoS 정책을 할당하는 동시에 SVM에 속한 볼륨에도 QoS 정책을 할당할 수 있습니다.

|===
.관련 정보
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP 9 출시 주요 내용"^]

